Fix color output on FreeBSD
--HG--
branch : develop

diff --git a/scripts/ci-run b/scripts/ci-run
--- a/scripts/ci-run
+++ b/scripts/ci-run
@@ -12,7 +12,7 @@ PEP8_VIOLATIONS_REPORT=pep8-violations.xml
 TEST_DB=test_noc
 
 error_exit ( ) {
-    echo -e "\033[1;31m$PROGNAME: ${1:-'Unknown error'}\033[0m" 1>&2
+    printf "\033[1;31m$PROGNAME: ${1:-'Unknown error'}\033[0m\n" 1>&2
     echo "Terminating" 1>&2
     exit 1
 }
diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -10,7 +10,7 @@
 ## Helper functions definitions
 ##
 error_exit ( ) {
-    echo "\033[1;31m$PROGNAME: ${1:-'Unknown error'}\033[0m" 1>&2
+    printf "\033[1;31m$PROGNAME: ${1:-'Unknown error'}\033[0m\n" 1>&2
     echo "Terminating" 1>&2
     # Report status
     if [ ! -z "${UPGRADE_LOG}" ]; then
